#version 460 core

// Compute shader blocks
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

// Common
#include "../include/common.glsl"

// Shared includes
#include "../include/sharedStructures.glsl"
#include "../include/sharedUniforms.glsl"

// Coloring models
#include "../include/models/blinn_phong.glsl"

// Path tracing includes
#include "../include/pathTracing/structures.glsl"
#include "../include/pathTracing/sceneBuffers.glsl"

// Path tracing intersection functions
#include "../include/pathTracing/intersections.glsl"

// Final image writeout
layout(rgba32f, binding = 0) uniform image2D img_output;

void main() {

    // Calculate pixel uv
    const ivec2  pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 img_size = imageSize(img_output);

    // Error check on image size
    if (pixel_coords.x >= img_size.x || pixel_coords.y >= img_size.y) return;

    // Get screen space coords
    const vec2 uv = (vec2(pixel_coords) + 0.5) / vec2(img_size) * 2.0 - 1.0;

    // Get the aspect ratio
    const float aspectRatio = float(img_size.x) / float(img_size.y);

    // Get the ray direction that's in view space and put it into world space
    const float tanHalfFOV = tan(radians(u_FOV * 0.5)); // Helper value
    const vec3 rayDirView = normalize(vec3(uv, -1.0) * vec3(aspectRatio * tanHalfFOV, tanHalfFOV, 1.0));
    const vec3 rayDirWorld = (u_inverseView * vec4(rayDirView, 0.0)).xyz;

    // Construct the final ray
    const Ray ray = Ray(u_cameraPos, normalize(rayDirWorld));

    // Find the hit in the scene
    const HitInfo hit = rayScene(ray);

    // Color based on the hit
    vec3 col;
    if (hit.hit) {
        // Phong-shade to get the color
        col = blinnPhong(ray, hit, Material(vec3(0.4, 0.2, 0.8), vec3(0.0), 0.5, 0.0), ray.origin, Material(vec3(0.0), vec3(1.0), 0.0, 0.0));
    } else {
        // Sky Gradient
        const float t = 0.5 * (ray.direction.y + 1.0);
        col = (1.0 - t) * vec3(1.0) + t * vec3(0.5, 0.7, 1.0);
    }

    // Write to the image with the final hit color
    imageStore(img_output, pixel_coords, vec4(col, 1.0));
}
